#!/usr/bin/env bash

SRC_DIR="$XDG_DOCUMENTS_DIR/Projects/Personal/nixos-configs"

exportSystem() {
	DST=/etc/nixos
	sudo rm -rf "$DST"
	sudo cp -a "$SRC_DIR/system-config" "$DST"
}

exportHome() {
	DST="$XDG_CONFIG_HOME/home-manager"
	rm -rf "$DST"
	cp -a "$SRC_DIR/home-manager/tomm" "$DST"
}

if [ "$#" == 0 ]; then
	exportSystem &
	exportHome &
elif [[ "$1" == "system" ]]; then
	exportSystem &
elif [[ "$1" == "home" ]]; then
	exportHome &
fi
wait
