name: Format
on:
  push:
    paths:
      - "**/*.lua"
      - ".stylua.toml"
  pull_request:
    paths:
      - "**/*.lua"
      - ".stylua.toml"
jobs:
  format:
    name: Stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          curl -L https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip -o stylua.zip
          unzip stylua.zip -d stylua-bin
          sudo mv stylua-bin/stylua /usr/local/bin/
      - name: Format
        run: stylua --check . --config-path=.stylua.toml
